name: llm_tune
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.7
      - aiosignal==1.3.2
      - airportsdata==20250523
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - attrs==25.3.0
      - backoff==2.2.1
      - blake3==1.0.5
      - cachetools==6.0.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.4
      - datasets==3.6.0
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.1
      - fastapi==0.115.12
      - filelock==3.18.0
      - frozenlist==1.6.2
      - fsspec==2025.5.1
      - genson==1.3.0
      - gguf==0.17.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - llguidance==0.7.26
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markupsafe==3.0.2
      - mistral-common==1.5.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.8.0.87
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.84.0
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.14
      - outlines-core==0.1.26
      - packaging==25.0
      - partial-json-parser==0.2.1.1.post5
      - pillow==11.2.1
      - pip==25.1.1
      - pip-review==1.3.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - python-json-logger==3.3.0
      - pytorch-triton==3.3.1+gitc8757738
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - setuptools==80.9.0
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.8.0.dev20250603+cu128
      - torchaudio==2.8.0.dev20250603+cu128
      - torchvision==0.23.0.dev20250603+cu128
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - trl==0.18.1
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - unsloth==2025.3.3
      - urllib3==2.4.0
      - vllm==0.8.3
      - watchfiles==1.0.5
      - xformers==0.0.30
      - xgrammar==0.1.19
      - yarl==1.20.0
      - zipp==3.22.0
prefix: /home/will/miniconda3/envs/llm_tune
